#!/bin/bash -e

cd jupyterteam_widget
pip install -e .
jupyter nbextension install --py --symlink --overwrite --sys-prefix jupyterteam_widget
jupyter nbextension enable --py --sys-prefix jupyterteam_widget

