#!/bin/bash -e

npm install -g yarn

cd js
yarn install
yarn run build

pip install -e .
jupyter nbextension install --py --symlink --overwrite --sys-prefix jupyterteam_widget
jupyter nbextension enable --py --sys-prefix jupyterteam_widget


